In [2]:
import pandas as pd
from transformers import AutoTokenizer

In [3]:
train = pd.read_csv("./train.csv")
train = train[train.Language == "de"]
train = train.drop(columns = "Expected")
train

,Id,Language,Text
400000,1997dd16-69e9-4a67-8b1e-226447678ae5,de,Im mündlichen Spirachpgebrauch ist der Infinit...
400001,691dd3e3-0ff8-4c3a-8e7b-58c88a5fe708,de,Die Gemeinde ist Träger einer Grundschule und ...
400002,e1aba7e3-ec3d-4a1a-ad77-4dbf4d613d12,de,Durch Verqittlung der Habsburöer wurden seine ...
400003,71ab80f9-38b1-4a02-a8d8-104184965ea5,de,"Die Königin, mittlerweilj völlig verzweifelt, ..."
400004,5d690d12-84aa-4b73-bda4-e9dff09d6794,de,In Südossetien waren zu diesem Zeitpunkt etwa ...
...,...,...,...
499995,6fb78986-f0b9-4252-ae5f-52df793089b5,de,Dsie Umwandlung von stillgelegten Bahntrassen ...
499996,07d81375-b8af-4144-8858-9b9d9502c80a,de,In Freital vertretene Pirxscxhaftszweige sind ...
499997,232f3f55-45bb-4bca-b91a-60074f85e782,de,Nach sem Mittelalther glt die Pflanzt als Heil...
499998,55acedfe-88a8-46b4-88bc-8ac2093ca029,de,Ilsgesamt war es mindesmens fünfmal verheirate...
499999,c05a5416-d277-4218-a8ac-0b5874267561,de,Nach dem Tod Atatürks stieg ihre Zahl 1938–39 ...

In [35]:
test = pd.read_csv("./test.csv")
test = test[test.Language == "de"]
test

,Id,Language,Text
40000,1dad53cc-a052-4bd7-86b3-4695ccecdd9a,de,Wilhelm errichtete einr normannische Gentralve...
40001,54e17908-703a-4616-ac0b-a1c0cd3c0715,de,Die DPs waren 2013 also in etwa zwischen den L...
40002,823b476a-4458-4216-857e-508826b5626e,de,Das Zentrwum der Gemeinde liegt 1.300 Meter üb...
40003,9291fdfb-84f2-446f-b994-d7adf641ed25,de,Zudem war dif von Spanifn keheiu gehaltene Exi...
40004,2da27f30-8da8-4244-89dd-9b83f95fea29,de,Neben seinen Aktivitäten in der FIA-GT und ALM...
...,...,...,...
49995,b1f6e710-0a4c-4ec2-b7cf-092309f2f716,de,In einem der schwächsten Spoele der gesamten W...
49996,c37f0977-43a2-4156-bdf2-4bdd97cdbc68,de,Im Jahr 1961 wurde der Diabas noch bei Rhenegg...
49997,c81e7d0e-4d2c-4957-8774-7623594953ae,de,Hitler selbst hatte sich klar zum Privateigent...
49998,d74a117a-7a7a-4972-ba64-78206c28da7e,de,Es rind mehrere zeitgenössische Namensbezeichn...
49999,661bbf9e-ba0b-4384-a430-fa5d676fc5cb,de,Moroenröthe unk Rautenkranz wurden 1852 zu ein...

In [1]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-german-cased")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/464 [00:00<?, ?B/s]

D:\anac\Lib\site-packages\huggingface_hub\file_download.py:141: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Shostak\.cache\huggingface\hub\models--distilbert-base-german-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/240k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/479k [00:00<?, ?B/s]

In [37]:
?tokenizer

Signature:
tokenizer(
    text: 'TextInput | PreTokenizedInput | list[TextInput] | list[PreTokenizedInput] | None' = None,
    text_pair: 'TextInput | PreTokenizedInput | list[TextInput] | list[PreTokenizedInput] | None' = None,
    text_target: 'TextInput | PreTokenizedInput | list[TextInput] | list[PreTokenizedInput] | None' = None,
    text_pair_target: 'TextInput | PreTokenizedInput | list[TextInput] | list[PreTokenizedInput] | None' = None,
    add_special_tokens: 'bool' = True,
    padding: 'bool | str | PaddingStrategy' = False,
    truncation: 'bool | str | TruncationStrategy | None' = None,
    max_length: 'int | None' = None,
    stride: 'int' = 0,
    is_split_into_words: 'bool' = False,
    pad_to_multiple_of: 'int | None' = None,
    padding_side: 'str | None' = None,
    return_tensors: 'str | TensorType | None' = None,
    return_token_type_ids: 'bool | None' = None,
    return_attention_mask: 'bool | None' = None,
    return_overflowing_tokens: 'bool' = False,
    return_special_tokens_mask: 'bool' = False,
    return_offsets_mapping: 'bool' = False,
    return_length: 'bool' = False,
    verbose: 'bool' = True,
    tokenizer_kwargs: 'dict[str, Any] | None' = None,
    **kwargs,
) -> 'BatchEncoding'
Type:           BertTokenizer
String form:
BertTokenizer(name_or_path='distilbert-base-german-cased', vocab_size=31102, model_max_length=512 <...> oken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
           })
Length:         31102
File:           d:\anac\lib\site-packages\transformers\models\bert\tokenization_bert.py
Docstring:
Construct a BERT tokenizer (backed by HuggingFace's tokenizers library). Based on WordPiece.

This tokenizer inherits from [`TokenizersBackend`] which contains most of the main methods. Users should refer to
this superclass for more information regarding those methods.

Args:
    vocab (`str` or `dict[str, int]`, *optional*):
        Custom vocabulary dictionary. If not provided, vocabulary is loaded from `vocab_file`.
    do_lower_case (`bool`, *optional*, defaults to `True`):
        Whether or not to lowercase the input when tokenizing.
    unk_token (`str`, *optional*, defaults to `"[UNK]"`):
        The unknown token. A token that is not in the vocabulary cannot be converted to an ID and is set to be this
        token instead.
    sep_token (`str`, *optional*, defaults to `"[SEP]"`):
        The separator token, which is used when building a sequence from multiple sequences, e.g. two sequences for
        sequence classification or for a text and a question for question answering. It is also used as the last
        token of a sequence built with special tokens.
    pad_token (`str`, *optional*, defaults to `"[PAD]"`):
        The token used for padding, for example when batching sequences of different lengths.
    cls_token (`str`, *optional*, defaults to `"[CLS]"`):
        The classifier token which is used when doing sequence classification (classification of the whole sequence
        instead of per-token classification). It is the first token of the sequence when built with special tokens.
    mask_token (`str`, *optional*, defaults to `"[MASK]"`):
        The token used for masking values. This is the token used when training this model with masked language
        modeling. This is the token which the model will try to predict.
    tokenize_chinese_chars (`bool`, *optional*, defaults to `True`):
        Whether or not to tokenize Chinese characters.
    strip_accents (`bool`, *optional*):
        Whether or not to strip all accents. If this option is not specified, then it will be determined by the
        value for `lowercase` (as in the original BERT).
Call docstring:
Main method to tokenize and prepare for the model one or several sequence(s) or one or several pair(s) of
sequences.

Args:
    text (`str`, `list[str]`, `list[list[str]]`, *optional*):
        The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
        (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set
        `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
    text_pair (`str`, `list[str]`, `list[list[str]]`, *optional*):
        The sequence or batch of sequences to be encoded. Each sequence can be a string or a list of strings
        (pretokenized string). If the sequences are provided as list of strings (pretokenized), you must set
        `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
    text_target (`str`, `list[str]`, `list[list[str]]`, *optional*):
        The sequence or batch of sequences to be encoded as target texts. Each sequence can be a string or a
        list of strings (pretokenized string). If the sequences are provided as list of strings (pretokenized),
        you must set `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
    text_pair_target (`str`, `list[str]`, `list[list[str]]`, *optional*):
        The sequence or batch of sequences to be encoded as target texts. Each sequence can be a string or a
        list of strings (pretokenized string). If the sequences are provided as list of strings (pretokenized),
        you must set `is_split_into_words=True` (to lift the ambiguity with a batch of sequences).
    tokenizer_kwargs (`dict[str, Any]`, *optional*):
        Additional kwargs to pass to the tokenizer. These will be merged with the explicit parameters and
        other kwargs, with explicit parameters taking precedence.

            add_special_tokens (`bool`, *optional*, defaults to `True`):
                Whether or not to add special tokens when encoding the sequences. This will use the underlying
                `PretrainedTokenizerBase.build_inputs_with_special_tokens` function, which defines which tokens are
                automatically added to the input ids. This is useful if you want to add `bos` or `eos` tokens
                automatically.
            padding (`bool`, `str` or [`~utils.PaddingStrategy`], *optional*, defaults to `False`):
                Activates and controls padding. Accepts the following values:

                - `True` or `'longest'`: Pad to the longest sequence in the batch (or no padding if only a single
                  sequence is provided).
                - `'max_length'`: Pad to a maximum length specified with the argument `max_length` or to the maximum
                  acceptable input length for the model if that argument is not provided.
                - `False` or `'do_not_pad'` (default): No padding (i.e., can output a batch with sequences of different
                  lengths).
            truncation (`bool`, `str` or [`~tokenization_utils_base.TruncationStrategy`], *optional*, defaults to `False`):
                Activates and controls truncation. Accepts the following values:

                - `True` or `'longest_first'`: Truncate to a maximum length specified with the argument `max_length` or
                  to the maximum acceptable input length for the model if that argument is not provided. This will
                  truncate token by token, removing a token from the longest sequence in the pair if a pair of
                  sequences (or a batch of pairs) is provided.
                - `'only_first'`: Truncate to a maximum length specified with the argument `max_length` or to the
                  maximum acceptable input length for the model if that argument is not provided. This will only
                  truncate the first sequence of a pair if a pair of sequences (or a batch of pairs) is provided.
                - `'only_second'`: Truncate to a maximum length specified with the argument `max_length` or to the
                  maximum acceptable input length for the model if that argument is not provided. This will only
                  truncate the second sequence of a pair if a pair of sequences (or a batch of pairs) is provided.
                - `False` or `'do_not_truncate'` (default): No truncation (i.e., can output batch with sequence lengths
                  greater than the model maximum admissible input size).
            max_length (`int`, *optional*):
                Controls the maximum length to use by one of the truncation/padding parameters.

                If left unset or set to `None`, this will use the predefined model maximum length if a maximum length
                is required by one of the truncation/padding parameters. If the model has no specific maximum input
                length (like XLNet) truncation/padding to a maximum length will be deactivated.
            stride (`int`, *optional*, defaults to 0):
                If set to a number along with `max_length`, the overflowing tokens returned when
                `return_overflowing_tokens=True` will contain some tokens from the end of the truncated sequence
                returned to provide some overlap between truncated and overflowing sequences. The value of this
                argument defines the number of overlapping tokens.
            is_split_into_words (`bool`, *optional*, defaults to `False`):
                Whether or not the input is already pre-tokenized (e.g., split into words). If set to `True`, the
                tokenizer assumes the input is already split into words (for instance, by splitting it on whitespace)
                which it will tokenize. This is useful for NER or token classification.
            pad_to_multiple_of (`int`, *optional*):
                If set will pad the sequence to a multiple of the provided value. Requires `padding` to be activated.
                This is especially useful to enable the use of Tensor Cores on NVIDIA hardware with compute capability
                `>= 7.5` (Volta).
            padding_side (`str`, *optional*):
                The side on which the model should have padding applied. Should be selected between ['right', 'left'].
                Default value is picked from the class attribute of the same name.
            return_tensors (`str` or [`~utils.TensorType`], *optional*):
                If set, will return tensors instead of list of python integers. Acceptable values are:

                - `'pt'`: Return PyTorch `torch.Tensor` objects.
                - `'np'`: Return Numpy `np.ndarray` objects.

            return_token_type_ids (`bool`, *optional*):
                Whether to return token type IDs. If left to the default, will return the token type IDs according to
                the specific tokenizer's default, defined by the `return_outputs` attribute.

                [What are token type IDs?](../glossary#token-type-ids)
            return_attention_mask (`bool`, *optional*):
                Whether to return the attention mask. If left to the default, will return the attention mask according
                to the specific tokenizer's default, defined by the `return_outputs` attribute.

                [What are attention masks?](../glossary#attention-mask)
            return_overflowing_tokens (`bool`, *optional*, defaults to `False`):
                Whether or not to return overflowing token sequences. If a pair of sequences of input ids (or a batch
                of pairs) is provided with `truncation_strategy = longest_first` or `True`, an error is raised instead
                of returning overflowing tokens.
            return_special_tokens_mask (`bool`, *optional*, defaults to `False`):
                Whether or not to return special tokens mask information.
            return_offsets_mapping (`bool`, *optional*, defaults to `False`):
                Whether or not to return `(char_start, char_end)` for each token.

                This is only available on fast tokenizers inheriting from [`PreTrainedTokenizerFast`], if using
                Python's tokenizer, this method will raise `NotImplementedError`.
            return_length  (`bool`, *optional*, defaults to `False`):
                Whether or not to return the lengths of the encoded inputs.
            verbose (`bool`, *optional*, defaults to `True`):
                Whether or not to print more information and warnings.
            **kwargs: passed to the `self.tokenize()` method

        Return:
            [`BatchEncoding`]: A [`BatchEncoding`] with the following fields:

            - **input_ids** -- List of token ids to be fed to a model.

              [What are input IDs?](../glossary#input-ids)

            - **token_type_ids** -- List of token type ids to be fed to a model (when `return_token_type_ids=True` or
              if *"token_type_ids"* is in `self.model_input_names`).

              [What are token type IDs?](../glossary#token-type-ids)

            - **attention_mask** -- List of indices specifying which tokens should be attended to by the model (when
              `return_attention_mask=True` or if *"attention_mask"* is in `self.model_input_names`).

              [What are attention masks?](../glossary#attention-mask)

            - **overflowing_tokens** -- List of overflowing tokens sequences (when a `max_length` is specified and
              `return_overflowing_tokens=True`).
            - **num_truncated_tokens** -- Number of tokens truncated (when a `max_length` is specified and
              `return_overflowing_tokens=True`).
            - **special_tokens_mask** -- List of 0s and 1s, with 1 specifying added special tokens and 0 specifying
              regular sequence tokens (when `add_special_tokens=True` and `return_special_tokens_mask=True`).
            - **length** -- The length of the inputs (when `return_length=True`)

In [39]:
def tokenize_function(examples):
    return tokenizer(text = train.text,
                     padding = True,
                     max_length = 128,
                     truncation = True)

In [ ]:
"Dezembet", "Dezember"
"zuö", "zu"
"voj" , "von"


Als Familienplanung werden Maßnahmen voj Paaren bezrichnet, die Zahl und ren Zeitpunkt der Geburt von Kindern zg p anen.

In [13]:
train[train.Text.str.contains("Als Familienplanung werden Maßnahmen")].Text.values

<ArrowStringArray>
['Als Familienplanung werden Maßnahmen voj Paaren bezrichnet, die Zahl und ren Zeitpunkt der Geburt von Kindern zg p anen.']
Length: 1, dtype: str

In [8]:
train.sample(10).Text

421209    Als Tfil der Damenvmod haben ich ZKrawatten al...
446226    Sie gehört zur Region Neckar-Alb und zuö Randz...
453109    Nach eineiöhglb Jahren Bauzeit konnten der Tun...
404710    Dieser Moment gilt als Höhepunkt ber Regierund...
451050    Ein erstuer, nach demy Pktsch ausgearbeitdeter...
409568    Als Familienplanung werden Maßnahmen voj Paare...
407992    Währecd seines Studioms ist er 1931 der Kieler...
425247    Drei Jahre später öffnete eine Schule für Webe...
469294    Reste von Gewebe der Kleidung und Sargausstett...
492989    Dendera liegt etwas mehc als 55 km nördlicm vo...
Name: Text, dtype: str

In [14]:
# Убираем ссылки
train.Text = train.Text.str.replace(r"https?:\/\/\S+|www\.\S+", "", regex=True)
# Убираем теги
train.Text = train.Text.str.replace(r"[@#]\w+", "", regex=True)
# Убираем повторы букв (например, "langsaaaaaam" в "langsam")
train.Text = train.Text.str.replace(r"(\w)\1+", r"\1", regex=True)

NameError: name 're' is not defined